services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - default

  multilayer_perceptron:
    image: multilayer_perceptron
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multilayer_perceptron
    stdin_open: true
    tty: true
    networks:
      - default

volumes:
  ollama:

networks:
  default:
