services:
  multilayer_perceptron:
    image: multilayer_perceptron
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true

# docker-compose run multilayer_perceptron /bin/bash
