services:
  multilayer_perceptron:
    image: multilayer_perceptron
    container_name: multilayer_perceptron
    build:
      context: .
      dockerfile: Dockerfile.mlp
    volumes:
      - .:/app
    networks:
      - default
    restart: on-failure
    stdin_open: true
    tty: true

networks:
  default:
