research_task:
  description: >
    You are a software engineer who has been tasked with
    finding all relevant information related to the question {topic}.
  instructions: >
    Using the tools available to you, search the wikipedia page
    for information related to the question {topic}.
  error_handling: >
    If the tool returns an error:
    - Retry with a refined query.
    - If the issue persists, provide a summary of your attempts and note the problem.
  expected_output: >
    A summary of the information found in the wikipedia page related to the question {topic}.

  agent: researcher

engineer_task:
  description: >
    You are a software engineer who has been tasked with analyzing the information
    provided by the researcher to find the answer to the question {topic}.
  instructions: >
    Analyze the information provided by the researcher and find the answer to the question {topic}.
    If you need more information, ask the researcher for additional details.
  error_handling: >
    If the information provided is insufficient:
    - Ask the researcher for more information.
    - If the issue persists, provide a summary of your attempts and note the problem.
  expected_output: >
    The answer to the question {topic} based on the information provided by the researcher.
  agent: engineer